### ISSUE TITLE
键盘音有延迟

### ISSUE THREAD

**Issue by CLDXiang** [Kaiyiwing/qwerty-learner-vscode#1]
RT

**Comment by Kaiyiwing** [comment]
Node 播放声音是个很麻烦的问题，写播放库的作者要考虑到 node 跨平台，所以要给每个平台找一个适合的底层播放器，然后做上层封装。目前使用的是node-wav-player，其原理很简单，根据不同的平台调用命令行播放器播放对应的文件，中间会有不好处理的延迟。
我会继续研究一下其他需要播放声音的插件是怎么处理延迟的问题
