### ISSUE TITLE
设置了音标 好像不起效果啊

### ISSUE THREAD

**Issue by wodesj33** [Kaiyiwing/qwerty-learner-vscode#10]
设置了音标 好像不起效果啊
![image](https://user-images.githubusercontent.com/8235472/111592351-a46fc580-8803-11eb-9eee-738c3c8f6701.png)

**Comment by Kaiyiwing** [comment]
目前偶现的 bug 为，在软件开启的状态下，使用 GUI 界面修改软件配置会出现bug。推测为，当使用 GUI 修改界面时，vsc 会将修改后的配置写入到本地的配置文件，而写入的操作会被本插件拦截，导致错误。

建议您打开 vsc 配置界面，点击右上角此按钮 
![image](https://user-images.githubusercontent.com/44634134/111593178-a5552700-8804-11eb-8334-c392f9313122.png)

搜索文件中是否有该配置 `"qwerty-learner.phonetic": "us",`
大概率会出现此种情况` "qwerty-learner.phonetic": `
自行补充为` "qwerty-learner.phonetic": "us",` 即可

**Comment by 0900304132** [comment]
> 目前偶现的 bug 为，在软件开启的状态下，使用 GUI 界面修改软件配置会出现bug。推测为，当使用 GUI 修改界面时，vsc 会将修改后的配置写入到本地的配置文件，而写入的操作会被本插件拦截，导致错误。
> 
> 建议您打开 vsc 配置界面，点击右上角此按钮
> ![image](https://user-images.githubusercontent.com/44634134/111593178-a5552700-8804-11eb-8334-c392f9313122.png)
> 
> 搜索文件中是否有该配置 `"qwerty-learner.phonetic": "us",`
> 大概率会出现此种情况`"qwerty-learner.phonetic":`
> 自行补充为` "qwerty-learner.phonetic": "us",` 即可

他可能是用的程序员词典 , 这个词典没有音标.
