### ISSUE TITLE
不能播放键盘声音

### ISSUE THREAD

**Issue by 0900304132** [Kaiyiwing/qwerty-learner-vscode#11]
播放键盘声音需要最小的node版本是多少. 
我的node版本是12.16.3 , 一直没有键盘声.
win7 node版本官方只支持到13.x

**Comment by Kaiyiwing** [comment]
我们使用的是 https://github.com/futomi/node-wav-player 来播放键盘声音，按其描述是支持 Node.js 4+ 版本

**Comment by 0900304132** [comment]
谢谢  我自己再调查下
