### ISSUE TITLE
关于发音问题

### ISSUE THREAD

**Issue by dianjie** [Kaiyiwing/qwerty-learner-vscode#16]
[cloudmusic-vscode](https://github.com/YXL76/cloudmusic-vscode)项目使用的播放好像是这个[rodio](https://github.com/RustAudio/rodio)

**Comment by Kaiyiwing** [comment]
我看了一下 cloudmusic-vscode，看起来是用 rust 实现了播放声音的模块，然后编译成 wasm 让 nodejs 调用. 
有时间我研究下，看看能不能借鉴一下

**Comment by dianjie** [comment]
> 我看了一下 cloudmusic-vscode，看起来是用 rust 实现了播放声音的模块，然后编译成 wasm 让 nodejs 调用.
> 有时间我研究下，看看能不能借鉴一下

也可以使用audio播放发音的前提是要替换VS Code的[ffmpeg](https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases)动态链接库，而且要每次更新 VS Code 都需重新替换

相关链接：

- [https://github.com/nondanee/vsc-netease-music](https://github.com/nondanee/vsc-netease-music)

- [https://marketplace.visualstudio.com/items?itemName=kangping.video](https://marketplace.visualstudio.com/items?itemName=kangping.video)
