### ISSUE TITLE
VS Code版本兼容问题

### ISSUE THREAD

**Issue by VitaminC1989** [Kaiyiwing/qwerty-learner-vscode#2]
如图
![image](https://user-images.githubusercontent.com/35803403/108317395-2d8ddf80-71f9-11eb-92aa-768cda59a2a1.png)

**Comment by Kaiyiwing** [comment]
建议升级一下 VSCode，目前最新版本为 1.53.0

**Comment by VitaminC1989** [comment]
更新vscode版本 成功安装了 感谢！
