### ISSUE TITLE
希望加入发音和自定义词库

### ISSUE THREAD

**Issue by MisakaMikoto-35c5** [Kaiyiwing/qwerty-learner-vscode#3]
希望在单词出现的时候加一个可配置的发音，和一个可以导入的自定义词库。

**Comment by Kaiyiwing** [comment]
非常感谢您的关注！

1. 发音我进行过尝试，目前发音使用的是有道的开放 API，通过 http 请求返回 mp3 文件，但 node 生态下没有鲁棒性强的 mp3 播放库，我尝过绝大多数播放库，均没有比较好的效果。
著名的 彩虹屁 插件，采取的是开启一个本地的 web 服务器，使用网页去播放声音，我个人感觉这种方式有点过重。所以还在考虑解决方案。
2. 自定义词库有开发计划，但可能需要一段时间。如有需要的词库建议参考项目内的词典格式生成 json 文件，发起 pr。

**Comment by LassaFever** [comment]
那能不能先加入音标呀

**Comment by Misng** [comment]
我不要求发音，有音标就好。​:smile:​

**Comment by Kaiyiwing** [comment]
> 我不要求发音，有音标就好。​😄​

这个会在近期更新

**Comment by hansonfang** [comment]
如果可以接入有道词典或者金山词霸这类的自定义单词本就好了

**Comment by Kaiyiwing** [comment]
已添加音标功能

**Comment by stonedreamforest** [comment]
发音还是建议有一个。顺便找了些库不知道是否符合。
https://github.com/googleapis/nodejs-text-to-speech
https://github.com/IonicaBizau/text-to-speech-js
https://github.com/marak/say.js/
https://github.com/watson-developer-cloud/text-to-speech-nodejs

**Comment by Kaiyiwing** [comment]
目前是有可靠的音频来源(有道开放 API)，通过 http 请求返回 mp3 文件，但没有找到合适的 mp3 播放库。
