### ISSUE TITLE
关于罚抄模式的问题

### ISSUE THREAD

**Issue by xxxuuu** [Kaiyiwing/qwerty-learner-vscode#30]
貌似目前实现中罚抄模式是不断重复一个 chapter

这与我想象中的有些出入，更接近“循环模式”

我理解的罚抄模式应该是存在拼写错误则重复当前 chapter，否则继续下一个 chapter

如果作者觉得这种方式可以接受，我可以提交一个 PR

**Comment by Kaiyiwing** [comment]
🐶 最省事的解决方案： 原模式改名为 循环模式，然后增加一个新版的罚抄模式，在 readme 上写清楚就好
