### ISSUE TITLE
单词提示功能

### ISSUE THREAD

**Issue by Misng** [Kaiyiwing/qwerty-learner-vscode#5]
我一开始以为这个是单词提示功能呢，比如我想写 second 结果写成 scond ，这时底边出现一个提示。是好的。

不过这个，貌似会耗资源些。​:sweat_smile:​

**Comment by Kaiyiwing** [comment]
这个需求可以试一下 [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
