### ISSUE TITLE
换个思路？

### ISSUE THREAD

**Issue by iuv** [Kaiyiwing/qwerty-learner-vscode#6]
做这个的目的大家都理解
就是希望上班的时候可以悄悄的背背单词
那是不是可以基于web版本的改造一个work版本的页面
打开work版本页面看到的就跟vscode一样，然后单词、音标、语音这些就都可以有了
只要放在合适的位置上，其他人也注意不到就可以了

**Comment by Kaiyiwing** [comment]
ohhhhhh
这个 idea 有点意思，摸鱼带师

**Comment by onewesong** [comment]
哈哈 太骚了

**Comment by lovitus** [comment]
> 做这个的目的大家都理解
> 就是希望上班的时候可以悄悄的背背单词
> 那是不是可以基于web版本的改造一个work版本的页面
> 打开work版本页面看到的就跟vscode一样，然后单词、音标、语音这些就都可以有了
> 只要放在合适的位置上，其他人也注意不到就可以了

搞起来!!!

**Comment by Kaiyiwing** [comment]
🤔 
我觉得这个 idea 可能不适合这个项目，我最初的想法是 coder 可以在写代码累的时候摸鱼，并且可以随时切换回写代码的状态。

但隐约感觉这种“反向伪装”的 idea 可以做更酷的东西出来

**Comment by iuv** [comment]
嗯，这不重要，只是看到有人提出希望在插件里还原Web版本的功能
由此想到，与其做大量功能适配插件不如改web来的容易
哈哈，问题我关了吧
