### ISSUE TITLE
是否考虑增加音标

### ISSUE THREAD

**Issue by tangaoo** [Kaiyiwing/qwerty-learner-vscode#7]
项目很棒！
后期是否考虑增加音标。能美音、英音可选就更棒了。

**Comment by Kaiyiwing** [comment]
抱歉，最近有 ddl 忘记这个 feature 了
已经添加这个功能了，在vscode更新就能看到了，需要在设置里手动开启，因为我个人觉得加上音标后信息有点过多，所以默认是关闭的。
